services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - hf_cache:/app/.cache/huggingface
      - models_data:/app/models
      - animals_data:/app/data

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api

volumes:
  hf_cache:
  models_data: 
  animals_data:
  