FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN useradd -m -u 1000 appuser

COPY requirements.txt .
RUN  uv pip install --no-cache-dir --system -r requirements.txt

COPY src/ ./src/
COPY configs ./configs/
COPY scripts/ ./scripts/
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh  && \
    mkdir -p /app/models /app/data /app/.cache/huggingface && \
    chown -R appuser:appuser /app
    
ENV HF_HOME=/app/.cache/huggingface
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=300s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
CMD ["./entrypoint.sh"]
