server {
    listen 80;

    client_max_body_size 10M;

    resolver 127.0.0.11 valid=10s;
    set $api_upstream http://api:8000;

    location /api/ {
        proxy_pass $api_upstream;
    }

    location /animals/ {
        proxy_pass $api_upstream;
    }

    location /docs {
        proxy_pass $api_upstream;
    }

    location /openapi.json {
        proxy_pass $api_upstream;
    }

    location / {
        set $front_upstream http://frontend:80;
        proxy_pass $front_upstream;
    }
}